## **Introduction**

Have you ever come across some valuable data on a website and wished you could access and use it in your research? Did you get discouraged from using useful data from a website because you found the job of writing it down by hand and transferring it to a spreadsheet daunting? Have you ever spent a substantial amount of time trying to copy and paste data from a website with plenty of frustration and headache? If you have found yourself in any of these and similar situations, then this write up is for you. I will highlight the basics of harvesting data from websites, commonly known as web scraping using `R` programming language. I start with the moist common form of data that most financial analysts and economists have interest in: tabular data. In future write ups, I will delve deeper into scrapping websites for text and other types of data and scrapping data that spans multiple web pages of a website. The basics in this section should meet the needs of most unsophisticated users but watch out for more advanced applications of web scrapping. 

## **The Target Website and Data**
I have conveniently chosen [wikipedia world population data site](https://en.wikipedia.org/wiki/World_population). The webpage title is `World population`. The webpage contains several tables with world population data broken down by time and continents sourced from the United Nations Population Department (UNPD) ^[You can visit the site on https://en.wikipedia.org/wiki/World_population].               